# Generated by Django 5.1.3 on 2024-12-09 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branches', '0002_remove_branches_address'),
        ('Department', '0003_departments_address'),
        ('Doctors', '0002_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='product/images/')),
                ('degree', models.TextField(max_length=10000)),
                ('branch', models.ManyToManyField(related_name='doctors', to='Branches.branches')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctors.designation')),
                ('practice_day', models.ManyToManyField(related_name='doctors', to='Doctors.weekly_days')),
                ('specialities', models.ManyToManyField(related_name='doctors', to='Department.departments')),
            ],
        ),
    ]
