# Generated by Django 5.1.3 on 2024-12-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0003_departments_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='address',
        ),
    ]
